In [6]:
# squeeze and unsqueeze are used to add or remove dimensions of size 1.
import torch
a = torch.rand(1,2)
print(a.shape)
b = a.unsqueeze(0)
print(b.shape)
c = a.squeeze(0)
print(c.shape)
d = a.unsqueeze(1)
print(d.shape)
e = a.squeeze(1)
print(e.shape)




# copying tensors; want a seperate copy of the tensor
m = torch.rand(2,2)
n = m.clone()
assert m is not n
print(torch.eq(m,n))

m[0][1]=3
print(n)



torch.Size([1, 2])
torch.Size([1, 1, 2])
torch.Size([2])
torch.Size([1, 1, 2])
torch.Size([1, 2])
tensor([[True, True],
        [True, True]])
tensor([[0.6663, 0.5476],
        [0.4932, 0.3015]])


In [7]:
x =torch.empty(5,3)
print(x)
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x)
print(empty_like_x.shape)

# similarly, zeros_like, ones_like, rand_like

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [12]:
# turn off the autograd engine
a = torch.rand(2,2, requires_grad=True)
print(a)
b= a.clone()
print(b) #inherates the requires_grad property
c = a.detach().clone() #no computation history
print(c)

print(a)

tensor([[0.6976, 0.4845],
        [0.6780, 0.4050]], requires_grad=True)
tensor([[0.6976, 0.4845],
        [0.6780, 0.4050]], grad_fn=<CloneBackward0>)
tensor([[0.6976, 0.4845],
        [0.6780, 0.4050]])
tensor([[0.6976, 0.4845],
        [0.6780, 0.4050]], requires_grad=True)


In [11]:
# tensor broadcasting
rand = torch.rand(2,4)
doubled = rand*(torch.ones(2,1)*2)
double = rand*(torch.ones(1,4)*2)
print(rand)
print(doubled)
print(double)


tensor([[0.6626, 0.0788, 0.0374, 0.9307],
        [0.9772, 0.3155, 0.0400, 0.9812]])
tensor([[1.3252, 0.1577, 0.0748, 1.8615],
        [1.9543, 0.6310, 0.0801, 1.9623]])
tensor([[1.3252, 0.1577, 0.0748, 1.8615],
        [1.9543, 0.6310, 0.0801, 1.9623]])
